### ISSUE TITLE
iOS 10 Maps version

### ISSUE THREAD

**Issue by sejersbol** [mkko/UserTrackingButton#3]
The iOS 10 user tracking button in Apple Maps has changed appearance. In iOS 10 Apple Maps (not MKUserTrackingBarButtonItem) they have filled arrows instead of the rounded tint color filled box. Do you have any plans for making a version of your very nice UserTrackingButton that mimics this design?

**Comment by mkko** [comment]
Hi @sejersbol, and my sincerest apologies for not seeing this. I haven't really been doing iOS stuff for a while, until now. I am planning to update this to match the latest version of iOS, and even better, I'd prefer to decouple the style from the button itself. I'll try to make the time for this.

**Comment by sejersbol** [comment]
Hi! With iOS 11 the tracking bar button was changed to a regular button - see https://developer.apple.com/documentation/mapkit/mkusertrackingbutton. I'm using this now. Is this what you also needed pre-iOS 11?

**Comment by mkko** [comment]
Thanks for pointing this out. That makes this project redundant and I'm happy to drop this. This project only makes sense for versions prior to iOS 11, so I'll update the description.

Thanks again!
